name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        vim: [vim, nvim]

    steps:
    - uses: actions/checkout@v1
    - name: Install Vim
      run: |
        case ${{ matrix.vim }} in
          vim)
            sudo add-apt-repository -yu ppa:jonathonf/vim && sudo apt-get install -qq vim
            ;;
          nvim)
            curl -L https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz | tar xz && echo "::add-path::$PWD/nvim-linux64/bin"
            ;;
        esac
    - name: Run tests
      run: make check VIM=${{ matrix.vim }}
